# Cloudflare Pages configuration for Second Brain Web Frontend
# This is only for the frontend part of the application
# Backend API will be deployed separately (likely to Cloudflare Workers or another service)

# Default configuration (staging)
name = "second-brain-web-staging"
compatibility_date = "2025-01-01"

# Production environment (used when deploying with tags)
[env.production]
name = "second-brain-web-prod"
compatibility_date = "2025-01-01"

# For Cloudflare Pages, the build configuration is primarily handled
# through the dashboard or GitHub Actions workflow
# The headers and redirects are handled by _headers and _redirects files
