/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripPlannerRouteImport } from './routes/trip-planner'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as MealTrackerRouteImport } from './routes/meal-tracker'
import { Route as DrawingsRouteImport } from './routes/drawings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripPlannerIndexRouteImport } from './routes/trip-planner.index'
import { Route as MealTrackerIndexRouteImport } from './routes/meal-tracker.index'
import { Route as DrawingsIndexRouteImport } from './routes/drawings.index'
import { Route as TripPlannerAddRouteImport } from './routes/trip-planner.add'
import { Route as TripPlannerIdRouteImport } from './routes/trip-planner.$id'
import { Route as MealTrackerAddRouteImport } from './routes/meal-tracker.add'
import { Route as DrawingsNewRouteImport } from './routes/drawings.new'
import { Route as DrawingsIdRouteImport } from './routes/drawings.$id'
import { Route as DemoCouponsRouteImport } from './routes/demo/coupons'
import { Route as AuthSuccessRouteImport } from './routes/auth.success'
import { Route as AuthErrorRouteImport } from './routes/auth.error'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as TripPlannerIdEditRouteImport } from './routes/trip-planner.$id.edit'
import { Route as SharedTripsShareTokenRouteImport } from './routes/shared.trips.$shareToken'
import { Route as MealTrackerEditIdRouteImport } from './routes/meal-tracker.edit.$id'
import { Route as TripPlannerIdItineraryAddRouteImport } from './routes/trip-planner.$id.itinerary.add'
import { Route as TripPlannerIdItineraryItemIdEditRouteImport } from './routes/trip-planner.$id.itinerary.$itemId.edit'

const TripPlannerRoute = TripPlannerRouteImport.update({
  id: '/trip-planner',
  path: '/trip-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MealTrackerRoute = MealTrackerRouteImport.update({
  id: '/meal-tracker',
  path: '/meal-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsRoute = DrawingsRouteImport.update({
  id: '/drawings',
  path: '/drawings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripPlannerIndexRoute = TripPlannerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TripPlannerRoute,
} as any)
const MealTrackerIndexRoute = MealTrackerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MealTrackerRoute,
} as any)
const DrawingsIndexRoute = DrawingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DrawingsRoute,
} as any)
const TripPlannerAddRoute = TripPlannerAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => TripPlannerRoute,
} as any)
const TripPlannerIdRoute = TripPlannerIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TripPlannerRoute,
} as any)
const MealTrackerAddRoute = MealTrackerAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => MealTrackerRoute,
} as any)
const DrawingsNewRoute = DrawingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DrawingsRoute,
} as any)
const DrawingsIdRoute = DrawingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DrawingsRoute,
} as any)
const DemoCouponsRoute = DemoCouponsRouteImport.update({
  id: '/demo/coupons',
  path: '/demo/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSuccessRoute = AuthSuccessRouteImport.update({
  id: '/auth/success',
  path: '/auth/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const TripPlannerIdEditRoute = TripPlannerIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TripPlannerIdRoute,
} as any)
const SharedTripsShareTokenRoute = SharedTripsShareTokenRouteImport.update({
  id: '/shared/trips/$shareToken',
  path: '/shared/trips/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const MealTrackerEditIdRoute = MealTrackerEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => MealTrackerRoute,
} as any)
const TripPlannerIdItineraryAddRoute =
  TripPlannerIdItineraryAddRouteImport.update({
    id: '/itinerary/add',
    path: '/itinerary/add',
    getParentRoute: () => TripPlannerIdRoute,
  } as any)
const TripPlannerIdItineraryItemIdEditRoute =
  TripPlannerIdItineraryItemIdEditRouteImport.update({
    id: '/itinerary/$itemId/edit',
    path: '/itinerary/$itemId/edit',
    getParentRoute: () => TripPlannerIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coupons': typeof CouponsRoute
  '/dashboard': typeof DashboardRoute
  '/drawings': typeof DrawingsRouteWithChildren
  '/meal-tracker': typeof MealTrackerRouteWithChildren
  '/notes': typeof NotesRoute
  '/profile': typeof ProfileRoute
  '/trip-planner': typeof TripPlannerRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/success': typeof AuthSuccessRoute
  '/demo/coupons': typeof DemoCouponsRoute
  '/drawings/$id': typeof DrawingsIdRoute
  '/drawings/new': typeof DrawingsNewRoute
  '/meal-tracker/add': typeof MealTrackerAddRoute
  '/trip-planner/$id': typeof TripPlannerIdRouteWithChildren
  '/trip-planner/add': typeof TripPlannerAddRoute
  '/drawings/': typeof DrawingsIndexRoute
  '/meal-tracker/': typeof MealTrackerIndexRoute
  '/trip-planner/': typeof TripPlannerIndexRoute
  '/meal-tracker/edit/$id': typeof MealTrackerEditIdRoute
  '/shared/trips/$shareToken': typeof SharedTripsShareTokenRoute
  '/trip-planner/$id/edit': typeof TripPlannerIdEditRoute
  '/trip-planner/$id/itinerary/add': typeof TripPlannerIdItineraryAddRoute
  '/trip-planner/$id/itinerary/$itemId/edit': typeof TripPlannerIdItineraryItemIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coupons': typeof CouponsRoute
  '/dashboard': typeof DashboardRoute
  '/notes': typeof NotesRoute
  '/profile': typeof ProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/success': typeof AuthSuccessRoute
  '/demo/coupons': typeof DemoCouponsRoute
  '/drawings/$id': typeof DrawingsIdRoute
  '/drawings/new': typeof DrawingsNewRoute
  '/meal-tracker/add': typeof MealTrackerAddRoute
  '/trip-planner/$id': typeof TripPlannerIdRouteWithChildren
  '/trip-planner/add': typeof TripPlannerAddRoute
  '/drawings': typeof DrawingsIndexRoute
  '/meal-tracker': typeof MealTrackerIndexRoute
  '/trip-planner': typeof TripPlannerIndexRoute
  '/meal-tracker/edit/$id': typeof MealTrackerEditIdRoute
  '/shared/trips/$shareToken': typeof SharedTripsShareTokenRoute
  '/trip-planner/$id/edit': typeof TripPlannerIdEditRoute
  '/trip-planner/$id/itinerary/add': typeof TripPlannerIdItineraryAddRoute
  '/trip-planner/$id/itinerary/$itemId/edit': typeof TripPlannerIdItineraryItemIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coupons': typeof CouponsRoute
  '/dashboard': typeof DashboardRoute
  '/drawings': typeof DrawingsRouteWithChildren
  '/meal-tracker': typeof MealTrackerRouteWithChildren
  '/notes': typeof NotesRoute
  '/profile': typeof ProfileRoute
  '/trip-planner': typeof TripPlannerRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/auth/success': typeof AuthSuccessRoute
  '/demo/coupons': typeof DemoCouponsRoute
  '/drawings/$id': typeof DrawingsIdRoute
  '/drawings/new': typeof DrawingsNewRoute
  '/meal-tracker/add': typeof MealTrackerAddRoute
  '/trip-planner/$id': typeof TripPlannerIdRouteWithChildren
  '/trip-planner/add': typeof TripPlannerAddRoute
  '/drawings/': typeof DrawingsIndexRoute
  '/meal-tracker/': typeof MealTrackerIndexRoute
  '/trip-planner/': typeof TripPlannerIndexRoute
  '/meal-tracker/edit/$id': typeof MealTrackerEditIdRoute
  '/shared/trips/$shareToken': typeof SharedTripsShareTokenRoute
  '/trip-planner/$id/edit': typeof TripPlannerIdEditRoute
  '/trip-planner/$id/itinerary/add': typeof TripPlannerIdItineraryAddRoute
  '/trip-planner/$id/itinerary/$itemId/edit': typeof TripPlannerIdItineraryItemIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coupons'
    | '/dashboard'
    | '/drawings'
    | '/meal-tracker'
    | '/notes'
    | '/profile'
    | '/trip-planner'
    | '/auth/callback'
    | '/auth/error'
    | '/auth/success'
    | '/demo/coupons'
    | '/drawings/$id'
    | '/drawings/new'
    | '/meal-tracker/add'
    | '/trip-planner/$id'
    | '/trip-planner/add'
    | '/drawings/'
    | '/meal-tracker/'
    | '/trip-planner/'
    | '/meal-tracker/edit/$id'
    | '/shared/trips/$shareToken'
    | '/trip-planner/$id/edit'
    | '/trip-planner/$id/itinerary/add'
    | '/trip-planner/$id/itinerary/$itemId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coupons'
    | '/dashboard'
    | '/notes'
    | '/profile'
    | '/auth/callback'
    | '/auth/error'
    | '/auth/success'
    | '/demo/coupons'
    | '/drawings/$id'
    | '/drawings/new'
    | '/meal-tracker/add'
    | '/trip-planner/$id'
    | '/trip-planner/add'
    | '/drawings'
    | '/meal-tracker'
    | '/trip-planner'
    | '/meal-tracker/edit/$id'
    | '/shared/trips/$shareToken'
    | '/trip-planner/$id/edit'
    | '/trip-planner/$id/itinerary/add'
    | '/trip-planner/$id/itinerary/$itemId/edit'
  id:
    | '__root__'
    | '/'
    | '/coupons'
    | '/dashboard'
    | '/drawings'
    | '/meal-tracker'
    | '/notes'
    | '/profile'
    | '/trip-planner'
    | '/auth/callback'
    | '/auth/error'
    | '/auth/success'
    | '/demo/coupons'
    | '/drawings/$id'
    | '/drawings/new'
    | '/meal-tracker/add'
    | '/trip-planner/$id'
    | '/trip-planner/add'
    | '/drawings/'
    | '/meal-tracker/'
    | '/trip-planner/'
    | '/meal-tracker/edit/$id'
    | '/shared/trips/$shareToken'
    | '/trip-planner/$id/edit'
    | '/trip-planner/$id/itinerary/add'
    | '/trip-planner/$id/itinerary/$itemId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CouponsRoute: typeof CouponsRoute
  DashboardRoute: typeof DashboardRoute
  DrawingsRoute: typeof DrawingsRouteWithChildren
  MealTrackerRoute: typeof MealTrackerRouteWithChildren
  NotesRoute: typeof NotesRoute
  ProfileRoute: typeof ProfileRoute
  TripPlannerRoute: typeof TripPlannerRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthErrorRoute: typeof AuthErrorRoute
  AuthSuccessRoute: typeof AuthSuccessRoute
  DemoCouponsRoute: typeof DemoCouponsRoute
  SharedTripsShareTokenRoute: typeof SharedTripsShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trip-planner': {
      id: '/trip-planner'
      path: '/trip-planner'
      fullPath: '/trip-planner'
      preLoaderRoute: typeof TripPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-tracker': {
      id: '/meal-tracker'
      path: '/meal-tracker'
      fullPath: '/meal-tracker'
      preLoaderRoute: typeof MealTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings': {
      id: '/drawings'
      path: '/drawings'
      fullPath: '/drawings'
      preLoaderRoute: typeof DrawingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip-planner/': {
      id: '/trip-planner/'
      path: '/'
      fullPath: '/trip-planner/'
      preLoaderRoute: typeof TripPlannerIndexRouteImport
      parentRoute: typeof TripPlannerRoute
    }
    '/meal-tracker/': {
      id: '/meal-tracker/'
      path: '/'
      fullPath: '/meal-tracker/'
      preLoaderRoute: typeof MealTrackerIndexRouteImport
      parentRoute: typeof MealTrackerRoute
    }
    '/drawings/': {
      id: '/drawings/'
      path: '/'
      fullPath: '/drawings/'
      preLoaderRoute: typeof DrawingsIndexRouteImport
      parentRoute: typeof DrawingsRoute
    }
    '/trip-planner/add': {
      id: '/trip-planner/add'
      path: '/add'
      fullPath: '/trip-planner/add'
      preLoaderRoute: typeof TripPlannerAddRouteImport
      parentRoute: typeof TripPlannerRoute
    }
    '/trip-planner/$id': {
      id: '/trip-planner/$id'
      path: '/$id'
      fullPath: '/trip-planner/$id'
      preLoaderRoute: typeof TripPlannerIdRouteImport
      parentRoute: typeof TripPlannerRoute
    }
    '/meal-tracker/add': {
      id: '/meal-tracker/add'
      path: '/add'
      fullPath: '/meal-tracker/add'
      preLoaderRoute: typeof MealTrackerAddRouteImport
      parentRoute: typeof MealTrackerRoute
    }
    '/drawings/new': {
      id: '/drawings/new'
      path: '/new'
      fullPath: '/drawings/new'
      preLoaderRoute: typeof DrawingsNewRouteImport
      parentRoute: typeof DrawingsRoute
    }
    '/drawings/$id': {
      id: '/drawings/$id'
      path: '/$id'
      fullPath: '/drawings/$id'
      preLoaderRoute: typeof DrawingsIdRouteImport
      parentRoute: typeof DrawingsRoute
    }
    '/demo/coupons': {
      id: '/demo/coupons'
      path: '/demo/coupons'
      fullPath: '/demo/coupons'
      preLoaderRoute: typeof DemoCouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/success': {
      id: '/auth/success'
      path: '/auth/success'
      fullPath: '/auth/success'
      preLoaderRoute: typeof AuthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip-planner/$id/edit': {
      id: '/trip-planner/$id/edit'
      path: '/edit'
      fullPath: '/trip-planner/$id/edit'
      preLoaderRoute: typeof TripPlannerIdEditRouteImport
      parentRoute: typeof TripPlannerIdRoute
    }
    '/shared/trips/$shareToken': {
      id: '/shared/trips/$shareToken'
      path: '/shared/trips/$shareToken'
      fullPath: '/shared/trips/$shareToken'
      preLoaderRoute: typeof SharedTripsShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-tracker/edit/$id': {
      id: '/meal-tracker/edit/$id'
      path: '/edit/$id'
      fullPath: '/meal-tracker/edit/$id'
      preLoaderRoute: typeof MealTrackerEditIdRouteImport
      parentRoute: typeof MealTrackerRoute
    }
    '/trip-planner/$id/itinerary/add': {
      id: '/trip-planner/$id/itinerary/add'
      path: '/itinerary/add'
      fullPath: '/trip-planner/$id/itinerary/add'
      preLoaderRoute: typeof TripPlannerIdItineraryAddRouteImport
      parentRoute: typeof TripPlannerIdRoute
    }
    '/trip-planner/$id/itinerary/$itemId/edit': {
      id: '/trip-planner/$id/itinerary/$itemId/edit'
      path: '/itinerary/$itemId/edit'
      fullPath: '/trip-planner/$id/itinerary/$itemId/edit'
      preLoaderRoute: typeof TripPlannerIdItineraryItemIdEditRouteImport
      parentRoute: typeof TripPlannerIdRoute
    }
  }
}

interface DrawingsRouteChildren {
  DrawingsIdRoute: typeof DrawingsIdRoute
  DrawingsNewRoute: typeof DrawingsNewRoute
  DrawingsIndexRoute: typeof DrawingsIndexRoute
}

const DrawingsRouteChildren: DrawingsRouteChildren = {
  DrawingsIdRoute: DrawingsIdRoute,
  DrawingsNewRoute: DrawingsNewRoute,
  DrawingsIndexRoute: DrawingsIndexRoute,
}

const DrawingsRouteWithChildren = DrawingsRoute._addFileChildren(
  DrawingsRouteChildren,
)

interface MealTrackerRouteChildren {
  MealTrackerAddRoute: typeof MealTrackerAddRoute
  MealTrackerIndexRoute: typeof MealTrackerIndexRoute
  MealTrackerEditIdRoute: typeof MealTrackerEditIdRoute
}

const MealTrackerRouteChildren: MealTrackerRouteChildren = {
  MealTrackerAddRoute: MealTrackerAddRoute,
  MealTrackerIndexRoute: MealTrackerIndexRoute,
  MealTrackerEditIdRoute: MealTrackerEditIdRoute,
}

const MealTrackerRouteWithChildren = MealTrackerRoute._addFileChildren(
  MealTrackerRouteChildren,
)

interface TripPlannerIdRouteChildren {
  TripPlannerIdEditRoute: typeof TripPlannerIdEditRoute
  TripPlannerIdItineraryAddRoute: typeof TripPlannerIdItineraryAddRoute
  TripPlannerIdItineraryItemIdEditRoute: typeof TripPlannerIdItineraryItemIdEditRoute
}

const TripPlannerIdRouteChildren: TripPlannerIdRouteChildren = {
  TripPlannerIdEditRoute: TripPlannerIdEditRoute,
  TripPlannerIdItineraryAddRoute: TripPlannerIdItineraryAddRoute,
  TripPlannerIdItineraryItemIdEditRoute: TripPlannerIdItineraryItemIdEditRoute,
}

const TripPlannerIdRouteWithChildren = TripPlannerIdRoute._addFileChildren(
  TripPlannerIdRouteChildren,
)

interface TripPlannerRouteChildren {
  TripPlannerIdRoute: typeof TripPlannerIdRouteWithChildren
  TripPlannerAddRoute: typeof TripPlannerAddRoute
  TripPlannerIndexRoute: typeof TripPlannerIndexRoute
}

const TripPlannerRouteChildren: TripPlannerRouteChildren = {
  TripPlannerIdRoute: TripPlannerIdRouteWithChildren,
  TripPlannerAddRoute: TripPlannerAddRoute,
  TripPlannerIndexRoute: TripPlannerIndexRoute,
}

const TripPlannerRouteWithChildren = TripPlannerRoute._addFileChildren(
  TripPlannerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CouponsRoute: CouponsRoute,
  DashboardRoute: DashboardRoute,
  DrawingsRoute: DrawingsRouteWithChildren,
  MealTrackerRoute: MealTrackerRouteWithChildren,
  NotesRoute: NotesRoute,
  ProfileRoute: ProfileRoute,
  TripPlannerRoute: TripPlannerRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthErrorRoute: AuthErrorRoute,
  AuthSuccessRoute: AuthSuccessRoute,
  DemoCouponsRoute: DemoCouponsRoute,
  SharedTripsShareTokenRoute: SharedTripsShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
